### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by Tycho10101** [NotAwesome2/MCGalaxy-CustomModels#4]
i was making a kirby model but i found some issues once i put it in my server

Blockbench:

    Inside:
![inside](https://user-images.githubusercontent.com/107083420/226491099-745aeddb-a9f4-4f65-b59e-3ca6c601937c.png)

    Outside:
![outside](https://user-images.githubusercontent.com/107083420/226491307-a5f28b9b-81a8-4354-9883-aecce9749baa.png)

Classicube:

    Inside:
![inside cc](https://user-images.githubusercontent.com/107083420/226491383-e33fcb26-0850-4e33-9cbe-6392e5ff1767.png)

    Outside:
![outside cc](https://user-images.githubusercontent.com/107083420/226491428-06bbf514-7e4c-4f1f-9318-ce546f024a86.png)

**Comment by Tycho10101** [comment]
https://discord.com/channels/375484033427046404/984661216729399346/1087528837442719835
issue solved

**Comment by Goodlyay** [comment]
For posterity or those who don't want to open Discord: this issue is caused because MCGalaxy thinks that Kirby's arms are like humanoid model arms, and is adjusting them to be thinner due to the kirby skin appearing to be a thin-armed skin. The thinning adjusts the UV map, which causes red to appear unexpectedly.

The solution is to remove "humanrightarm" and "humanleftarm" tags from the arm model names.
